# Generated by Django 4.2.5 on 2023-09-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEmployees',
            fields=[
                ('customer_employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_employee_firstname', models.CharField(max_length=255)),
                ('customer_employee_lastname', models.CharField(max_length=255)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRoles',
            fields=[
                ('employee_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_role_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=255)),
                ('employee_last_name', models.CharField(max_length=255)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
                ('employee_role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.employeeroles')),
            ],
        ),
        migrations.CreateModel(
            name='FailureReasons',
            fields=[
                ('failure_reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('failure_reason_title', models.CharField(max_length=500)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=255)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_begin_date', models.DateTimeField(default=None, null=True)),
                ('project_end_date', models.DateTimeField(default=None, null=True)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
                ('customer_employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.customeremployees')),
                ('employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.employees')),
                ('failure_reason', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.failurereasons')),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.status')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(default=None, null=True)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.projects')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('invoice_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_item', models.CharField(max_length=255)),
                ('purchase_price', models.FloatField(default=None, null=True)),
                ('sell_price', models.FloatField(default=None, null=True)),
                ('invoice_item_quantity', models.IntegerField(default=None, null=True)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
                ('invoice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.invoices')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEmployeeTels',
            fields=[
                ('customer_employee_tel_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_employee_tel', models.CharField(default=None, max_length=255, null=True)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
                ('customer_employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.customeremployees')),
            ],
        ),
        migrations.AddField(
            model_name='customeremployees',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.customers'),
        ),
        migrations.CreateModel(
            name='CustomerEmployeeEmails',
            fields=[
                ('customer_employee_email_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_employee_email', models.CharField(default=None, max_length=255, null=True)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
                ('customer_employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.customeremployees')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEmployeeAddresses',
            fields=[
                ('customer_employee_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default=None, max_length=255, null=True)),
                ('is_disabled', models.BooleanField(default=None, null=True)),
                ('customer_employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.customeremployees')),
            ],
        ),
    ]
